CREATE TABLE users (
    userID VARCHAR(50) UNIQUE NOT NULL PRIMARY KEY,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    score INT NOT NULL DEFAULT 80,
    live BOOLEAN DEFAULT FALSE NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sessions (
    sessionID SERIAL PRIMARY KEY,
    userID VARCHAR(50) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ongoing BOOLEAN DEFAULT TRUE NOT NULL,
    FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE
);

CREATE TABLE session_updates(
    sessionUpdateID SERIAL PRIMARY KEY,
    sessionID INT NOT NULL,
    updateType INT NOT NULL CHECK (updateType IN (0, 1)),
    updateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (sessionID) REFERENCES sessions(sessionID) ON DELETE CASCADE
);